CREATE DATABASE Bebidas
GO
USE Bebidas
GO

CREATE TABLE BEBIDAS
(
ID_BEBIDA INT IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(50),
PRECIO MONEY

CONSTRAINT PK_BEBIDAS PRIMARY KEY (ID_BEBIDA)
);

CREATE TABLE SOCIOS
(
ID_SOCIO INT IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50)

CONSTRAINT PK_SOCIOS PRIMARY KEY (ID_SOCIO)
);

CREATE TABLE EMPLEADOS
(
LEGAJO INT IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50)

CONSTRAINT PK_EMPLEADOS PRIMARY KEY (LEGAJO)
);

CREATE TABLE FORMA_PAGO
(
ID_PAGO INT IDENTITY(1,1) NOT NULL,
TIPO VARCHAR(50)

CONSTRAINT PK_FORMA_PAGO PRIMARY KEY (ID_PAGO)
);

CREATE TABLE FACTURAS
(
NRO_FACTURA INT IDENTITY(1,1) NOT NULL,
ID_SOCIO INT,
ID_EMPLEADO INT,
ID_PAGO INT,
FECHA DATE

CONSTRAINT PK_FACTURAS PRIMARY KEY (NRO_FACTURA)

CONSTRAINT FK_FACTURAS_SOCIOS FOREIGN KEY (ID_SOCIO)
REFERENCES SOCIOS (ID_SOCIO),

CONSTRAINT FK_FACTURAS_EMPLEADOS FOREIGN KEY (ID_EMPLEADO)
REFERENCES EMPLEADOS (LEGAJO),

CONSTRAINT FK_FACTURAS_FORMA_PAGO FOREIGN KEY (ID_PAGO)
REFERENCES FORMA_PAGO (ID_PAGO)
);

CREATE TABLE DETALLE_FACTURA
(
ID_DETALLE INT IDENTITY(1,1),
NRO_FACTURA INT NOT NULL,
ID_BEBIDA INT,
CANTIDAD INT,
PRECIO MONEY

CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (ID_DETALLE)

CONSTRAINT FK_DETALLE_FACTURA_FACTURAS FOREIGN KEY (NRO_FACTURA)
REFERENCES FACTURAS (NRO_FACTURA),

CONSTRAINT FK_DETALLE_FACTURA_BEBIDAS FOREIGN KEY (ID_BEBIDA)
REFERENCES BEBIDAS (ID_BEBIDA)
);

-- I N S E R T S

INSERT INTO FORMA_PAGO(TIPO) 
VALUES ('Efectivo'),
('Debito'),
('Credito'),
('Transferencia'),
('MODO'),
('Mercado Pago');

INSERT INTO SOCIOS (NOMBRE,APELLIDO)
VALUES ('Agus','Nieto'),
('Nato','Barrionuevo'),
('Javier','Milei'),
('Pity','Alvarez');

INSERT INTO EMPLEADOS (NOMBRE,APELLIDO)
VALUES ('Rulo','Castillo'),
('Gustavo','Cerati'),
('Leo','Messi'),
('Jessie','Pinkman');

INSERT INTO BEBIDAS(NOMBRE,PRECIO)
VALUES ('Smirnoff',3642.22), 
('Skyy',4258.51), 
('Bacardi',12218.17),
('Absolut',9692.13), 
('Capitan Morgan',3514.91), 
('Corona',1159.39),
('Imperial',927.44),
('Patagonia',1123.29),
('Stella Artois',1118.12),
('Heineken',765.47),
('Salta',843.46), 
('Quilmes',1010.42),
('Alma Mora',2301.87),
('Trapiche',3469.01),
('Viñas de Balbo',1789.41), 
('Colon',1365.02),
('Dada',2225.89),
('Norton',1419.04),
('Santa Julia',1453.87),
('Black Label J. Walker',23662.15),
('Coca Cola Zero',1575),
('Pepsi',946.08),
('Coca Cola',2383.5),
('Doble Cola',742.13),
('Cunnington',706.11);

--SPs GET
GO
CREATE PROCEDURE SP_GET_BEBIDA
@ID INT
AS
BEGIN
	SELECT ID_BEBIDA, NOMBRE, PRECIO 
	FROM BEBIDAS
	WHERE ID_BEBIDA = @ID
END;
GO

CREATE PROCEDURE SP_GET_FORMA_PAGO
AS
BEGIN
	SELECT ID_PAGO, TIPO
	FROM FORMA_PAGO
END;
GO

CREATE PROCEDURE SP_GET_SOCIOS
AS
BEGIN
	SELECT ID_SOCIO, NOMBRE, APELLIDO
	FROM SOCIOS
END;
GO

CREATE PROCEDURE SP_GET_EMPLEADOS
AS
BEGIN
	SELECT LEGAJO, NOMBRE, APELLIDO
	FROM EMPLEADOS
END;
GO
--SPs POST

CREATE PROCEDURE SP_POST_FACTURA
@FACTURA INT OUTPUT,
@SOCIO INT,
@EMPLEADO INT,
@PAGO INT
AS
BEGIN
	INSERT INTO FACTURAS (ID_SOCIO,ID_EMPLEADO,ID_PAGO,FECHA)
	VALUES (@SOCIO,@EMPLEADO,@PAGO,GETDATE())

	SET @FACTURA = SCOPE_IDENTITY();
END;
GO

CREATE PROCEDURE SP_POST_DETALLE
@FACTURA INT,
@BEBIDA INT,
@CANTIDAD INT,
@PRECIO MONEY
AS
BEGIN
	INSERT INTO DETALLE_FACTURA (NRO_FACTURA,ID_BEBIDA,CANTIDAD,PRECIO)
	VALUES (@FACTURA,@BEBIDA,@CANTIDAD,@PRECIO)
END;
GO

CREATE PROCEDURE SP_SCREEN_BEBIDAS
AS
BEGIN
	SELECT ID_BEBIDA, NOMBRE, PRECIO 
	FROM BEBIDAS
	ORDER BY NOMBRE
END;